### PR TITLE
Websocket API endpoints

### PR DESCRIPTION
**Pull request by kirushik**
This time I was too lazy to write proper ExDoc.

Usage example:

``` elixir
tape = Stockastic.Tickertape.new account, venue
for tick <- Stockastic.Tickertape.stream(tape) do
  IO.inspect tick
end
```

### CODE REVIEW

**Comment by QuinnWilton** [comment]
I like this a lot, thanks! It'll need a rebase because of another pull request I merged, but shouldn't be difficult to resolve. Are you alright doing that, or do you want me to?

**Comment by kirushik** [comment]
@ShaneWilton done rebasing.

**Comment by kirushik** [comment]
Should I also generate and commit html documentation files for publishing update docs to hex, or will it be compiled automagically?

**Comment by kirushik** [comment]
@ShaneWilton I'm a little bit shy to ask, but is everything alright with this pull request?
Can I enhance it somehow to make it mergeable, or is it just me being the only one guy out of 'Christmas mode' already?

**Comment by QuinnWilton** [comment]
@kirushik Nope, this looks perfect! Sorry, I'm still half AWOL, and thought I merged this a few days ago. Thanks for reminding me!

The documentation will be generated when I push a new build to Hex.

**Pull request merged**
